baseurl = "https://www.anmolsarma.in/"
title = "Anmol Sarma"
languageCode = "en-in"
DisqusShortname = "anmolsarma"
Copyright = "Except where noted otherwise, content licensed under a <a href='https://creativecommons.org/licenses/by/4.0/'>Creative Commons Attribution 4.0 International License</a>."

PygmentsCodeFences = true
pygmentsstyle = "emacs"
theme = "mumo"
Paginate = 1000

[menu]
    [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/"

    [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/"

    [[menu.main]]
    identifier = "talks"
    name       = "Talks"
    url        = "/tags/talks/"

