baseurl = "https://www.anmolsarma.in/"
title = "Anmol Sarma"
languageCode = "en-in"
DisqusShortname = "anmolsarma"
Copyright = "Except where noted otherwise, content on this webiste is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)."

PygmentsCodeFences = true
pygmentsstyle = "emacs"
theme = "mumo"
Paginate = 1000

[menu]
    [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/"

    [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

    [[menu.main]]
    identifier = "renders"
    name       = "Renders"
    url        = "/renders"

    [[menu.main]]
    identifier = "talks"
    name       = "Talks"
    url        = "/tags/talks/"

